default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password: Toru0424
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

test:
  <<: *default
  adapter: mysql2
  username: root
  password: Toru0424
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>